name: Deploy to githubPages

on:
  pull_requests:
    branches: [master]

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.16
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "dbeetoven" && git config user.email "beetovenson@gmail.com"
          npm run gh-pages-deploy
